# Generated by Django 2.1.7 on 2019-03-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibilité',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='Compatible',
            field=models.ManyToManyField(through='option.Compatibilité', to='version.Version'),
        ),
    ]
