# Generated by Django 2.1.7 on 2019-03-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_auto_20190312_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='Code_Option',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
