# Generated by Django 2.1.7 on 2019-03-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('option', '0003_auto_20190313_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compatibilité',
            new_name='Compatibilite',
        ),
    ]
