# Generated by Django 2.1.7 on 2019-03-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0004_auto_20190313_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilite',
            name='Default',
            field=models.BooleanField(default=False),
        ),
    ]
