# Generated by Django 2.1.7 on 2019-03-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0005_compatibilite_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibilite',
            name='option',
        ),
        migrations.RemoveField(
            model_name='compatibilite',
            name='version',
        ),
        migrations.RemoveField(
            model_name='option',
            name='Compatible',
        ),
        migrations.DeleteModel(
            name='Compatibilite',
        ),
    ]
