# Generated by Django 2.1.7 on 2019-03-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('option', '0009_remove_option_option_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='khra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
        ),
    ]
