# Generated by Django 2.1.7 on 2019-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
        ('option', '0010_khra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khra',
            name='option',
        ),
        migrations.RemoveField(
            model_name='khra',
            name='version',
        ),
        migrations.AddField(
            model_name='option',
            name='option_Version',
            field=models.ManyToManyField(through='option.Option_Version', to='version.Version'),
        ),
        migrations.DeleteModel(
            name='khra',
        ),
    ]
