# Generated by Django 2.1.7 on 2019-03-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0011_auto_20190317_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option_version',
            name='option',
        ),
        migrations.RemoveField(
            model_name='option_version',
            name='version',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_Version',
        ),
        migrations.DeleteModel(
            name='Option_Version',
        ),
    ]
