# Generated by Django 2.1.7 on 2019-06-21 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_auto_20190318_1154'),
        ('CompositionVehicule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule_compose',
            name='Version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='version.Version'),
            preserve_default=False,
        ),
    ]
