# Generated by Django 2.1.7 on 2019-03-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0012_auto_20190318_1154'),
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option_Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Default', models.BooleanField(default=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='option_Version',
            field=models.ManyToManyField(through='version.Option_Version', to='option.Option'),
        ),
    ]
