# Generated by Django 2.1.7 on 2019-03-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couleur', '0001_initial'),
        ('modele', '0002_modele_image'),
        ('option', '0004_auto_20190313_1521'),
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif_Couleur',
            fields=[
                ('tarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.Tarif')),
                ('Couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couleur.Couleur')),
            ],
            bases=('tarif.tarif',),
        ),
        migrations.CreateModel(
            name='Tarif_Option',
            fields=[
                ('tarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.Tarif')),
                ('Option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
            ],
            bases=('tarif.tarif',),
        ),
        migrations.CreateModel(
            name='Tarif_Version',
            fields=[
                ('tarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.Tarif')),
                ('Version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
            bases=('tarif.tarif',),
        ),
        migrations.AddField(
            model_name='tarif',
            name='Modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modele.Modele'),
        ),
    ]
