# Generated by Django 2.1.7 on 2019-03-14 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='Date_Debut',
            field=models.DateField(blank=None, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tarif',
            name='Date_Fin',
            field=models.DateField(blank=None, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tarif',
            name='Prix',
            field=models.FloatField(blank=None, default=0.0),
        ),
    ]
