# Generated by Django 2.1.7 on 2019-03-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0003_auto_20190317_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='Modele',
        ),
    ]
