# Generated by Django 2.1.7 on 2019-03-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modele', '0002_modele_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('Code_Couleur', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Nom_Couleur', models.CharField(max_length=100)),
                ('Colore', models.ManyToManyField(to='modele.Modele')),
            ],
        ),
    ]
