# Generated by Django 2.1.7 on 2019-02-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('Id_Marque', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom_Marque', models.CharField(max_length=100)),
                ('Logo_Marque', models.ImageField(blank=True, null=True, upload_to='Marque_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('Code_Modele', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom_Modele', models.CharField(max_length=100)),
                ('Id_Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Model_set', to='system_api.Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('Code_Version', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nom_Version', models.CharField(max_length=200)),
                ('Id_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Version_set', to='system_api.Modele')),
            ],
        ),
    ]
