# Generated by Django 2.1.7 on 2019-02-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compatible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('Id_Marque', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom_Marque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('Code_Modele', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom_Modele', models.CharField(max_length=100)),
                ('Id_Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_api.Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('Code_Option', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nom_Option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('Code_Version', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nom_Version', models.CharField(max_length=200)),
                ('Nom_Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_api.Modele')),
            ],
        ),
        migrations.AddField(
            model_name='compatible',
            name='Code_Option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_api.Option'),
        ),
        migrations.AddField(
            model_name='compatible',
            name='Code_Version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_api.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='compatible',
            unique_together={('Code_Version', 'Code_Option')},
        ),
    ]
