# Generated by Django 2.1.7 on 2019-02-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compatible',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='compatible',
            name='Code_Option',
        ),
        migrations.RemoveField(
            model_name='compatible',
            name='Code_Version',
        ),
        migrations.DeleteModel(
            name='Compatible',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
