# Generated by Django 2.1.7 on 2019-02-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marque',
            name='Logo_Marque',
        ),
    ]
