# Generated by Django 2.1.7 on 2019-02-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_api', '0002_remove_marque_logo_marque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='Id_modele',
            new_name='Id_Modele',
        ),
    ]
