# Generated by Django 2.1.7 on 2019-06-21 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('version', '0002_auto_20190318_1154'),
        ('couleur', '0001_initial'),
        ('option', '0012_auto_20190318_1154'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prix_Minimal', models.FloatField(blank=None, default=0.0)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Date_Annonce', models.DateField(blank=None, default=datetime.date.today)),
                ('Couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='couleur.Couleur')),
                ('Id_Automobiliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Automobiliste')),
                ('Options_Annonce', models.ManyToManyField(related_name='Annonces', to='option.Option')),
                ('Version', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images_Annonce', models.FileField(upload_to='Annonce/')),
                ('Annonce', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Images_Annonce', to='annonce.Annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.Annonce')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
            ],
        ),
    ]
