# Generated by Django 2.1.7 on 2019-03-21 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couleur', '0001_initial'),
        ('accounts', '0001_initial'),
        ('option', '0012_auto_20190318_1154'),
        ('version', '0002_auto_20190318_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=None, default=datetime.date.today)),
                ('montant', models.FloatField(blank=None, default=0.0)),
                ('reserver', models.BooleanField(default=False)),
                ('automobiliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Automobiliste')),
            ],
        ),
        migrations.CreateModel(
            name='List_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('Numero_Chassis', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Code_Couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couleur.Couleur')),
                ('Code_Version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
                ('Liste_Option', models.ManyToManyField(through='reservation.List_Option', to='option.Option')),
                ('Reservasion', models.ManyToManyField(through='reservation.Commande', to='accounts.Automobiliste')),
            ],
        ),
        migrations.AddField(
            model_name='list_option',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Vehicule'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Vehicule'),
        ),
    ]
