# Generated by Django 2.1.7 on 2019-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='Concessionnaire',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
